name: Validate CloudFormation Template

on:
  workflow_call:
    inputs:
      trigger_job:
        description: 'Trigger job'
        required: true
        type: string
        
jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: main
          
      - name: Checkout single-env-deployment repository
        uses: actions/checkout@v2
        with:
          repository: srikanth-1612/single-env-deployment
          ref: main
          path: single-env-deployment
        
      - name: Install AWS CLI V2
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Configure AWS credentials
        run: |
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region = ap-southeast-1" >> ~/.aws/config

      - name: Validate CloudFormation template
        run: |
          # Run cfn-lint to validate CloudFormation template
          aws cloudformation validate-template --template-body file://single-env-deployment/.github/workflows/cfn.yml
